export enum AuditLogType {
  UNKNOWN= -1,
  REQUEST_REG_SERVICE_CREATED ,
  REQUEST_UPDATE_SERVICE_CREATED ,
  REQUEST_TRANSFER_SERVICE_CREATED ,
  REQUEST_REMOVE_SERVICE_CREATED ,
  REQUEST_APPROVED ,
  REQUEST_REJECTED ,
  REQUEST_CHANGES_REQUEST ,
  REQUEST_UPDATED ,
  REQUEST_CANCELED,
}
