export enum RequestStatus {
  APPROVED = "STATUS.APPROVED",
  REJECTED = "STATUS.REJECTED",
  WAITING_FOR_APPROVAL = "STATUS.WAITING_FOR_APPROVAL",
  WAITING_FOR_CHANGES = "STATUS.WAITING_FOR_CHANGES"
}
